### ISSUE TITLE
TiledTexture与在逻辑层进行加载/卸载的区别？

### ISSUE THREAD

**Issue by HanetakaChou** [sienaiwun/Dx12Practice#1]
最近Virtual Texture比较火，我对于Demo中的TiledTexture比较感兴趣，但我对于这个技术存在一定困惑。
我目前理解的做法是维护多份贴图，在逻辑层（可以认为是负责资源加载/卸载的Streaming模块）随着摄像机的移动，进行贴图的加载/卸载操作。
目前新的API貌似允许ReserveTexture(D3D12)/SparseTexture(Vulkan)，这与传统的做法有什么本质上的区别，或者说优势（比如效率上提升或者是怎么样）？

**Comment by YuqiaoZhang** [comment]
> 最近Virtual Texture比较火，我对于Demo中的TiledTexture比较感兴趣。
> 我目前理解的做法是维护多份贴图，在逻辑层（可以认为是负责资源加载/卸载的Streaming模块）随着摄像机的移动，进行贴图的加载/卸载操作。
> 目前新的API貌似允许ReserveTexture(D3D12)/SparseTexture(Vulkan)，这与传统的做法有什么本质上的区别（比如效率上提升或者是怎么样）？

**Comment by sienaiwun** [comment]
理解上是一样的，只加载需要用到的纹素，哪些纹素需要加载，可以由绘制一次feedback pass来处理，也可以在前向绘制的时候写入到buffer之中，也可以通过逻辑语义（比如相邻地块之类的）进行加载。
硬件上的支持是这样，你设定tiled memory 到实际物理GPU resouces的映射关系之后，硬件帮你去做uv 映射，直接去采样，不用去采样indirect texture 再手动偏移缩放，再采样。
更重要的是，硬件支持对sampler的支持更好。不用关心mipmap之类的，也不用去考虑边缘的padding.
